# OLake Sync Job Configuration
# This defines the complete pipeline from MySQL to Iceberg

job:
  name: "mysql-to-iceberg-demo"
  description: "Demo pipeline for MySQL CDC to Iceberg via OLake"
  
  # Source configuration
  source:
    type: mysql
    connection:
      host: mysql
      port: 3306
      database: demo_db
      username: olake
      password: olake_pass
      
    # Replication settings
    replication:
      mode: cdc  # Change Data Capture
      initial_sync: true  # Do full load first, then CDC
      binlog_format: ROW
      server_id: 100
      
    # Tables to sync
    streams:
      - stream_name: users
        table_name: users
        primary_key: [id]
        cursor_field: updated_at
        sync_mode: incremental
        
      - stream_name: products
        table_name: products  
        primary_key: [id]
        cursor_field: updated_at
        sync_mode: incremental
        
      - stream_name: orders
        table_name: orders
        primary_key: [id] 
        cursor_field: order_date
        sync_mode: incremental
        
      - stream_name: user_sessions
        table_name: user_sessions
        primary_key: [id]
        cursor_field: last_activity
        sync_mode: incremental

  # Destination configuration  
  destination:
    type: iceberg
    connection:
      catalog_type: rest
      warehouse: s3a://iceberg-warehouse/
      catalog_uri: http://minio:9000
      
      # S3/MinIO settings
      s3_endpoint: http://minio:9000
      s3_access_key: minioadmin
      s3_secret_key: minioadmin123
      s3_path_style_access: true
      
    # Output configuration
    output:
      namespace: demo_lakehouse
      table_prefix: olake_
      
      # Partitioning
      partitioning:
        users: 
          - field: created_at
            transform: month
        orders:
          - field: order_date  
            transform: month
          - field: status
            transform: identity
        user_sessions:
          - field: login_time
            transform: day

  # Sync configuration
  sync:
    frequency: "0 */5 * * * *"  # Every 5 minutes
    batch_size: 1000
    parallelism: 2
    
  # Monitoring
  monitoring:
    enabled: true
    log_level: info
    metrics:
      - rows_processed
      - sync_duration
      - errors
